# Generated by Django 3.2.5 on 2021-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shop', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('visitors', models.PositiveIntegerField()),
                ('earnings', models.IntegerField()),
            ],
        ),
    ]
